# Generated by Django 5.2.17 on 2026-10-05 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jornadas', '0017_momento_backfill_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaOpenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo', models.CharField(db_index=True, help_text='Qué parte del sistema hizo la llamada.', max_length=60)),
                ('origen_id', models.CharField(blank=True, max_length=40)),
                ('metodo', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('endpoint', models.CharField(db_index=True, help_text='Ruta de la API, ej. /v1/chat/completions.', max_length=120)),
                ('modelo', models.CharField(blank=True, db_index=True, max_length=80)),
                ('peticion', models.JSONField(blank=True, null=True)),
                ('peticion_cruda', models.BinaryField(blank=True, null=True)),
                ('peticion_content_type', models.CharField(blank=True, max_length=200)),
                ('peticion_headers', models.JSONField(blank=True, default=dict)),
                ('peticion_bytes', models.PositiveBigIntegerField(default=0)),
                ('estado', models.CharField(choices=[('ok', 'OK (2xx)'), ('error_http', 'Error HTTP (OpenAI respondió con error)'), ('error_red', 'Error de red / sin respuesta')], db_index=True, max_length=12)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('respuesta_cruda', models.TextField(blank=True, help_text='Cuerpo de la respuesta cuando no es JSON.')),
                ('respuesta_headers', models.JSONField(blank=True, default=dict)),
                ('respuesta_bytes', models.PositiveBigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, help_text='x-request-id de OpenAI, para soporte.', max_length=120)),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_total', models.PositiveIntegerField(blank=True, null=True)),
                ('iniciado_en', models.DateTimeField(db_index=True)),
                ('finalizado_en', models.DateTimeField()),
                ('duracion_ms', models.PositiveIntegerField(help_text='Desde que sale la petición hasta que llega la respuesta completa.')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_openai', to='jornadas.jornada')),
                ('momento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_openai', to='jornadas.momento')),
                ('origen_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_openai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Llamada a OpenAI',
                'verbose_name_plural': 'Llamadas a OpenAI',
                'ordering': ['-iniciado_en'],
                'indexes': [models.Index(fields=['origen_tipo', 'origen_id'], name='auditoria_l_origen__a9d74c_idx')],
            },
        ),
    ]
