# Generated by Django 5.2.17 on 2026-08-18 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(max_length=200)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='jornadas.jornada')),
            ],
            options={
                'unique_together': {('jornada', 'correo_institucional'), ('jornada', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_libre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('opciones', models.ManyToManyField(blank=True, related_name='respuestas', to='jornadas.opcionpregunta')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='participantes.participante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='jornadas.pregunta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_registradas', to='participantes.participante')),
            ],
            options={
                'unique_together': {('pregunta', 'mesa'), ('pregunta', 'participante')},
            },
        ),
    ]
