# Generated by Django 5.2.17 on 2026-08-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='es_vocero',
            field=models.BooleanField(default=False, help_text='Solo el vocero de una mesa puede enviar respuestas en momentos tipo mesa.'),
        ),
        migrations.AddField(
            model_name='participante',
            name='mesa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
