# Generated by Django 5.2.17 on 2026-09-15 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0006_momento_mesas_permitidas'),
        ('participantes', '0004_participante_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraccionMomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='participantes/extracciones/%Y/%m/')),
                ('nombre_archivo_original', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo — a la espera de revisión'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('preguntas_omitidas', models.JSONField(blank=True, default=list)),
                ('error_mensaje', models.TextField(blank=True)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracciones_momento_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones', to='jornadas.momento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones', to='participantes.participante')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracciones_momento_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracción de momento con IA (documento diligenciado)',
                'verbose_name_plural': 'Extracciones de momento con IA (documentos diligenciados)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
