# Generated by Django 5.2.17 on 2026-09-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0007_alter_pregunta_tipo_columnamatrizpregunta_and_more'),
        ('participantes', '0005_extraccionmomento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='columna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jornadas.columnamatrizpregunta'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jornadas.filamatrizpregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('pregunta', 'mesa', 'fila', 'columna'), ('pregunta', 'participante', 'fila', 'columna')},
        ),
    ]
