# Generated by Django 5.2.17 on 2026-09-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0010_alter_pregunta_tipo'),
        ('participantes', '0006_alter_respuesta_unique_together_respuesta_columna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaListaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filas_lista_creadas', to='participantes.participante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_lista', to='jornadas.pregunta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('pregunta', 'mesa', 'fila', 'columna'), ('pregunta', 'participante', 'fila', 'columna')},
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fila_lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participantes.filalistarespuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('pregunta', 'mesa', 'fila', 'columna'), ('pregunta', 'mesa', 'fila_lista', 'columna'), ('pregunta', 'participante', 'fila', 'columna'), ('pregunta', 'participante', 'fila_lista', 'columna')},
        ),
    ]
