# Generated by Django 5.2.17 on 2026-09-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0007_filalistarespuesta_alter_respuesta_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraccionmomento',
            name='responsable_detectado',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extraccionmomento',
            name='responsable_estado',
            field=models.CharField(choices=[('no_buscado', 'No se buscó (responsable indicado a mano)'), ('sin_dato', 'El documento no traía responsable'), ('emparejado', 'Emparejado con una persona'), ('ambiguo', 'Ambiguo — varias personas coinciden'), ('sin_coincidencia', 'Sin coincidencia')], default='no_buscado', max_length=20),
        ),
        migrations.AlterField(
            model_name='extraccionmomento',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracciones', to='participantes.participante'),
        ),
    ]
