# Generated by Django 5.2.17 on 2026-10-04 22:40

import django.db.models.deletion
from django.db import migrations, models


def marcar_escritas_en_version_1(apps, schema_editor):
    # Todo lo escrito antes de HU-91 quedó en la única versión que existía.
    ExtraccionMomento = apps.get_model('participantes', 'ExtraccionMomento')
    ExtraccionMomento.objects.filter(aprobado_en__isnull=False).update(version_escrita=1)


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0017_momento_backfill_creado_por'),
        ('participantes', '0009_responsable_estado_creado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extraccionmomento',
            name='participante_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracciones_sugeridas', to='participantes.participante'),
        ),
        migrations.AddField(
            model_name='extraccionmomento',
            name='version_escrita',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filalistarespuesta',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extraccionmomento',
            name='responsable_estado',
            field=models.CharField(choices=[('no_buscado', 'No se buscó (responsable indicado a mano)'), ('sin_dato', 'El documento no traía responsable'), ('emparejado', 'Emparejado con una persona'), ('ambiguo', 'Ambiguo — varias personas coinciden'), ('sin_coincidencia', 'Sin coincidencia'), ('creado', 'Creado a partir del documento'), ('con_respuestas', 'Ya tiene respuestas en el momento — hay que decidir')], default='no_buscado', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('pregunta', 'mesa', 'version', 'fila', 'columna'), ('pregunta', 'mesa', 'version', 'fila_lista', 'columna'), ('pregunta', 'participante', 'version', 'fila', 'columna'), ('pregunta', 'participante', 'version', 'fila_lista', 'columna')},
        ),
        migrations.RunPython(marcar_escritas_en_version_1, migrations.RunPython.noop),
    ]
