# Generated by Django 5.2.17 on 2026-08-18 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('contexto', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('individual', 'Respuesta individual'), ('mesa', 'Respuesta por mesa')], default='individual', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='jornadas.jornada')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('jornada', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('abierta', 'Abierta'), ('unica', 'Selección única'), ('multiple', 'Selección múltiple')], max_length=20)),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField()),
                ('obligatoria', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='jornadas.momento')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('momento', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='jornadas.pregunta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'orden')},
            },
        ),
    ]
