# Generated by Django 5.2.17 on 2026-08-19 02:43

from django.db import migrations, models
from django.utils.text import slugify


def rellenar_slugs_existentes(apps, schema_editor):
    """Los momentos que ya existían antes de este campo quedan con slug='' tras el AddField de
    abajo — eso viola la unique_together (jornada, slug) que se aplica a continuación si hay más
    de un momento en la misma jornada. Se rellenan aquí, con la misma lógica de colisión que usa
    Momento.save() en el modelo, antes de que esa restricción se cree."""
    Momento = apps.get_model('jornadas', 'Momento')
    for momento in Momento.objects.filter(slug='').order_by('jornada_id', 'orden'):
        base_slug = slugify(momento.titulo)[:250] or 'momento'
        slug = base_slug
        contador = 1
        while Momento.objects.filter(jornada_id=momento.jornada_id, slug=slug).exclude(pk=momento.pk).exists():
            contador += 1
            slug = f'{base_slug}-{contador}'
        momento.slug = slug
        momento.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='momento',
            unique_together={('jornada', 'orden')},
        ),
        migrations.AddField(
            model_name='momento',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.RunPython(rellenar_slugs_existentes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='momento',
            unique_together={('jornada', 'orden'), ('jornada', 'slug')},
        ),
    ]
