# Generated by Django 5.2.17 on 2026-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0002_alter_momento_unique_together_momento_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='categorias_semilla',
            field=models.JSONField(blank=True, default=list, help_text='Lista opcional de categorías temáticas predefinidas para este momento (ej. ["principios", "riesgos y dilemas", ...]). Si está vacía, los temas se descubren automáticamente con BERTopic, igual que hoy.'),
        ),
    ]
