# Generated by Django 5.2.17 on 2026-09-04 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0003_momento_categorias_semilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='mesas_permitidas',
            field=models.JSONField(blank=True, default=list, help_text='Lista opcional de números de mesa que pueden ver/responder esta pregunta (solo aplica en momentos tipo mesa). Vacía = visible para todas las mesas, igual que hoy.'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('dependencia', 'Dependencia')], default='dependencia', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
