# Generated by Django 5.2.17 on 2026-09-04 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0004_jornada_propietario_pregunta_mesas_permitidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='propietario',
        ),
        migrations.AddField(
            model_name='jornada',
            name='propietarios',
            field=models.ManyToManyField(blank=True, related_name='jornadas_propias', to=settings.AUTH_USER_MODEL),
        ),
    ]
