# Generated by Django 5.2.17 on 2026-09-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0005_remove_jornada_propietario_jornada_propietarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='mesas_permitidas',
            field=models.JSONField(blank=True, default=list, help_text='Lista opcional de números de mesa que pueden ver/participar en este momento completo (solo aplica en momentos tipo mesa). Vacía = visible para todas las mesas.'),
        ),
    ]
