# Generated by Django 5.2.17 on 2026-09-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0006_momento_mesas_permitidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('unica', 'Selección única'), ('multiple', 'Selección múltiple'), ('matriz', 'Matriz comparativa (filas × columnas)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ColumnaMatrizPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='jornadas.pregunta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='FilaMatrizPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='jornadas.pregunta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'orden')},
            },
        ),
    ]
