# Generated by Django 5.2.17 on 2026-09-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0007_alter_pregunta_tipo_columnamatrizpregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='roles_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista opcional de nombres de rol que pueden ver/participar en este momento. Vacía = visible para todos los roles.'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='roles_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista opcional de nombres de rol que pueden ver/responder esta pregunta. Vacía = visible para todos los roles, igual que hoy.'),
        ),
        migrations.CreateModel(
            name='RolJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_definidos', to='jornadas.jornada')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('jornada', 'nombre')},
            },
        ),
    ]
