# Generated by Django 5.2.17 on 2026-09-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0008_momento_roles_permitidos_pregunta_roles_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='depende_de_opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_condicionadas', to='jornadas.opcionpregunta'),
        ),
    ]
