# Generated by Django 5.2.17 on 2026-09-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0009_pregunta_depende_de_opcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('unica', 'Selección única'), ('multiple', 'Selección múltiple'), ('matriz', 'Matriz comparativa (filas × columnas, cantidad fija)'), ('lista', 'Lista de registros (columnas fijas, filas las agrega quien responde)')], max_length=20),
        ),
    ]
