# Generated by Django 4.2.30 on 2026-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0012_pregunta_filas_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='permite_carga_archivo',
            field=models.BooleanField(default=False, help_text='Si los participantes pueden subir ellos mismos un documento diligenciado para este momento, para que la IA lo transcriba. Apagado = solo un administrador puede hacerlo.'),
        ),
    ]
