# Generated by Django 5.2.17 on 2026-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0014_jornadaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaasset',
            name='texto',
            field=models.TextField(blank=True, help_text='Guía de marca escrita (colores, tipografía, tono). Solo aplica a tipo system_design.'),
        ),
        migrations.AlterField(
            model_name='jornadaasset',
            name='archivo',
            field=models.FileField(blank=True, upload_to='jornadas/assets/%Y/%m/'),
        ),
    ]
