# Generated by Django 5.2.17 on 2026-09-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0015_jornadaasset_texto_alter_jornadaasset_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='momento',
            name='momento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momentos_derivados', to='jornadas.momento'),
        ),
        migrations.AddField(
            model_name='momento',
            name='origen_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='momento',
            name='visibilidad',
            field=models.CharField(choices=[('privado', 'Privado — solo yo puedo reutilizarlo'), ('publico', 'Público — cualquiera puede usarlo como plantilla')], db_index=True, default='privado', max_length=10),
        ),
    ]
