# Generated by Django 5.2.17 on 2026-10-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0017_momento_backfill_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaasset',
            name='contenido_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jornadaasset',
            name='contenido_estado',
            field=models.CharField(choices=[('sin_leer', 'Sin leer'), ('leyendo', 'Leyendo'), ('listo', 'Listo'), ('error', 'Error')], default='sin_leer', max_length=10),
        ),
        migrations.AddField(
            model_name='jornadaasset',
            name='contenido_metodo',
            field=models.CharField(blank=True, choices=[('texto_extraido', 'Texto extraído del archivo'), ('vision', 'Leído con visión (IA)'), ('texto_escrito', 'Texto escrito al subirlo')], max_length=20),
        ),
        migrations.AddField(
            model_name='jornadaasset',
            name='contenido_texto',
            field=models.TextField(blank=True, help_text='Lo que el análisis lee del asset (texto extraído, transcripción o descripción con visión). Se calcula una vez y se reutiliza.'),
        ),
        migrations.AddField(
            model_name='jornadaasset',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Qué es y para qué sirve, escrito por quien lo sube. Le llega al modelo junto al contenido.'),
        ),
        migrations.AddField(
            model_name='jornadaasset',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre legible del adjunto (si no se da, se usa el nombre del archivo).', max_length=200),
        ),
        migrations.AddField(
            model_name='jornadaasset',
            name='usar_en_presentacion',
            field=models.BooleanField(default=True, help_text='Si la imagen entra a la diagramación de presentaciones y a las infografías.'),
        ),
        migrations.AlterField(
            model_name='jornadaasset',
            name='tipo',
            field=models.CharField(choices=[('asset', 'Asset'), ('system_design', 'System design'), ('documento', 'Documento')], default='asset', max_length=20),
        ),
    ]
