# Generated by Django 5.2.17 on 2026-08-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='estadisticas',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='topicos',
        ),
        migrations.AddField(
            model_name='reporte',
            name='analisis',
            field=models.JSONField(blank=True, default=dict, help_text='Estructura jerárquica: participación + análisis por momento y por pregunta (descripción, tipo de gráfica, valores característicos). Ver analitica/analysis.py.'),
        ),
    ]
