# Generated by Django 5.2.17 on 2026-08-19 02:43

from django.db import migrations, models
from django.utils import timezone


def rellenar_slugs_existentes(apps, schema_editor):
    """Los reportes que ya existían antes de este campo quedan con slug='' tras el AddField de
    abajo — como el campo es unique=True, eso solo puede aplicarse (más de un reporte con el
    mismo '') si primero se rellenan con datos reales. Se usa creado_en (ya en hora de Colombia
    porque TIME_ZONE='America/Bogota' vía timezone.localtime) en vez de "ahora", para que el slug
    de un reporte viejo siga reflejando cuándo se generó de verdad."""
    Reporte = apps.get_model('analitica', 'Reporte')
    for reporte in Reporte.objects.filter(slug='').order_by('id'):
        momento_local = timezone.localtime(reporte.creado_en)
        base_slug = f'{reporte.jornada.slug}-{reporte.alcance}-{momento_local:%Y%m%d-%H%M}'
        slug = base_slug
        contador = 1
        while Reporte.objects.filter(slug=slug).exclude(pk=reporte.pk).exists():
            contador += 1
            slug = f'{base_slug}-{contador}'
        reporte.slug = slug
        reporte.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_remove_reporte_estadisticas_remove_reporte_topicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Autogenerado: jornada + alcance + fecha/hora local de Colombia — para poder distinguir reportes a simple vista, no solo por id.', max_length=250),
            preserve_default=False,
        ),
        migrations.RunPython(rellenar_slugs_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reporte',
            name='slug',
            field=models.SlugField(blank=True, help_text='Autogenerado: jornada + alcance + fecha/hora local de Colombia — para poder distinguir reportes a simple vista, no solo por id.', max_length=250, unique=True),
        ),
    ]
