# Generated by Django 5.2.17 on 2026-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0004_reporte_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='presentacion_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presentacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presentacion_generada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presentacion_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presentacion_modelo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
