# Generated by Django 5.2.17 on 2026-08-20 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0005_reporte_presentacion_error_and_more'),
        ('jornadas', '0003_momento_categorias_semilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisMomentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Mismo formato que un item de analisis.momentos[] en Reporte: momento_id, tipo, descripcion_general, preguntas[] (con valores_caracteristicos y metodo_valores).')),
                ('error_mensaje', models.TextField(blank=True)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='jornadas.momento')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_momento_ia_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de momento con IA (OpenAI)',
                'verbose_name_plural': 'Análisis de momento con IA (OpenAI)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
