# Generated by Django 5.2.17 on 2026-08-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0006_analisismomentoia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisismomentoia',
            name='resultado',
            field=models.JSONField(blank=True, default=dict, help_text='momento_id, tipo, resumen_ejecutivo, hallazgos[] (cada uno con titulo, descripcion, preguntas_relacionadas, tipo_grafica y datos) — ver analisis_ia_openai.py.'),
        ),
    ]
