# Generated by Django 5.2.17 on 2026-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0007_alter_analisismomentoia_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaanalisis',
            name='tipo',
            field=models.CharField(choices=[('local', 'Pipeline local (por pregunta/momento/jornada)'), ('gpt_momento', 'Análisis de momento completo vía OpenAI')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantillaanalisis',
            name='predeterminada',
            field=models.BooleanField(default=False, help_text='Solo una plantilla puede ser predeterminada POR TIPO — marcar una nueva desmarca automáticamente la anterior del mismo tipo, nunca las del otro tipo.'),
        ),
    ]
