# Generated by Django 5.2.17 on 2026-09-04 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0008_plantillaanalisis_tipo_and_more'),
        ('jornadas', '0006_momento_mesas_permitidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillaanalisis',
            name='tipo',
            field=models.CharField(choices=[('local', 'Pipeline local (por pregunta/momento/jornada)'), ('gpt_momento', 'Análisis de momento completo vía OpenAI'), ('gpt_jornada', 'Análisis de jornada completa vía OpenAI')], default='local', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalisisJornadaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='jornada_id, resumen_ejecutivo, hallazgos[] (cada uno con titulo, descripcion, momentos_relacionados, preguntas_relacionadas, tipo_grafica y datos) — ver analisis_ia_openai.py.')),
                ('error_mensaje', models.TextField(blank=True)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='jornadas.jornada')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_jornada_ia_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de jornada con IA (OpenAI)',
                'verbose_name_plural': 'Análisis de jornada con IA (OpenAI)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
