# Generated by Django 5.2.17 on 2026-09-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0009_alter_plantillaanalisis_tipo_analisisjornadaia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisjornadaia',
            name='resultado',
            field=models.JSONField(blank=True, default=dict, help_text='jornada_id, resumen_ejecutivo, hallazgos[] (cada uno con titulo, descripcion, momentos_relacionados, preguntas_relacionadas, transcripciones_relacionadas, tipo_grafica y datos) — ver analisis_ia_openai.py.'),
        ),
    ]
