# Generated by Django 5.2.17 on 2026-09-18 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0010_alter_analisisjornadaia_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfografiaJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('prompt_usado', models.TextField(blank=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infografias', to='analitica.reporte')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infografias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Infografía de jornada (IA)',
                'verbose_name_plural': 'Infografías de jornada (IA)',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='InfografiaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='analitica/infografias/%Y/%m/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('infografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='analitica.infografiajornada')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
