# Generated by Django 5.2.17 on 2026-09-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0014_infografiajornada_instrucciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisjornadaia',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general que escribió quien pidió el análisis — puede coincidir con Jornada.descripcion o no. Se guarda tal cual, sin normalizar.', max_length=4000),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='enfoque',
            field=models.CharField(choices=[('cualitativo', 'Cualitativo — sentido, matices y voces representativas'), ('cuantitativo', 'Cuantitativo — frecuencias, porcentajes y comparaciones'), ('mixto', 'Mixto — cifras y lectura interpretativa a la par (recomendado)')], default='mixto', help_text='Con qué enfoque leer los datos: cualitativo (voces y matices), cuantitativo (cifras y comparaciones) o mixto (ambos por igual, default).', max_length=15),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales de quien pidió el análisis (tono, público, cantidad de gráficos, idioma…) — mandan sobre el estilo y la estructura por defecto.', max_length=4000),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='prompt_usado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general que escribió quien pidió el análisis — puede coincidir con Jornada.descripcion o no. Se guarda tal cual, sin normalizar.', max_length=4000),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='contexto_momento',
            field=models.TextField(blank=True, help_text='Contexto propio de ESTE momento, además del contexto general de la jornada. Solo aplica cuando el alcance es un único momento.', max_length=4000),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='enfoque',
            field=models.CharField(choices=[('cualitativo', 'Cualitativo — sentido, matices y voces representativas'), ('cuantitativo', 'Cuantitativo — frecuencias, porcentajes y comparaciones'), ('mixto', 'Mixto — cifras y lectura interpretativa a la par (recomendado)')], default='mixto', help_text='Con qué enfoque leer los datos: cualitativo (voces y matices), cuantitativo (cifras y comparaciones) o mixto (ambos por igual, default).', max_length=15),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales de quien pidió el análisis (tono, público, cantidad de gráficos, idioma…) — mandan sobre el estilo y la estructura por defecto.', max_length=4000),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='instrucciones_momento',
            field=models.TextField(blank=True, help_text='Instrucciones propias de ESTE momento, además de las generales. Solo aplica cuando el alcance es un único momento.', max_length=4000),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='prompt_usado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general que escribió quien pidió el análisis — puede coincidir con Jornada.descripcion o no. Se guarda tal cual, sin normalizar.', max_length=4000),
        ),
        migrations.AddField(
            model_name='reporte',
            name='contexto_momento',
            field=models.TextField(blank=True, help_text='Contexto propio de ESTE momento, además del contexto general de la jornada. Solo aplica cuando el alcance es un único momento.', max_length=4000),
        ),
        migrations.AddField(
            model_name='reporte',
            name='enfoque',
            field=models.CharField(choices=[('cualitativo', 'Cualitativo — sentido, matices y voces representativas'), ('cuantitativo', 'Cuantitativo — frecuencias, porcentajes y comparaciones'), ('mixto', 'Mixto — cifras y lectura interpretativa a la par (recomendado)')], default='mixto', help_text='Con qué enfoque leer los datos: cualitativo (voces y matices), cuantitativo (cifras y comparaciones) o mixto (ambos por igual, default).', max_length=15),
        ),
        migrations.AddField(
            model_name='reporte',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales de quien pidió el análisis (tono, público, cantidad de gráficos, idioma…) — mandan sobre el estilo y la estructura por defecto.', max_length=4000),
        ),
        migrations.AddField(
            model_name='reporte',
            name='instrucciones_momento',
            field=models.TextField(blank=True, help_text='Instrucciones propias de ESTE momento, además de las generales. Solo aplica cuando el alcance es un único momento.', max_length=4000),
        ),
        migrations.AddField(
            model_name='reporte',
            name='prompt_usado',
            field=models.TextField(blank=True),
        ),
    ]
