# Generated by Django 5.2.17 on 2026-09-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0015_analisis_guiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='infografiajornada',
            name='analisis_jornada',
            field=models.ForeignKey(blank=True, help_text='Fija el AnalisisJornadaIA exacto del que salen los datos. Solo aplica con alcance de jornada (sin `momento`). Sin esto, se usa el más reciente completo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infografias', to='analitica.analisisjornadaia'),
        ),
        migrations.AddField(
            model_name='infografiajornada',
            name='analisis_momento',
            field=models.ForeignKey(blank=True, help_text='Fija el AnalisisMomentoIA exacto del que salen los datos. Solo aplica con `momento`. Sin esto, se usa el más reciente completo de ese momento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infografias', to='analitica.analisismomentoia'),
        ),
        migrations.AlterField(
            model_name='infografiajornada',
            name='reporte',
            field=models.ForeignKey(blank=True, help_text='Fija el Reporte (pipeline local) exacto del que salen los datos. Solo aplica con alcance de jornada (sin `momento`). Sin esto, se usa el más reciente completo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infografias', to='analitica.reporte'),
        ),
    ]
