# Generated by Django 5.2.17 on 2026-09-20 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0016_infografia_fija_analisis_exacto'),
        ('jornadas', '0017_momento_backfill_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('integral', 'Integral — un informe de toda la jornada'), ('por_momento', 'Por momento — un informe independiente por cada momento elegido')], max_length=12)),
                ('pipeline', models.CharField(choices=[('llm', 'LLM directo (sin BERTopic)'), ('bertopic_llm', 'BERTopic + LLM')], default='llm', max_length=15)),
                ('contexto', models.TextField(blank=True, help_text='Contexto general escrito por quien pide el análisis. Viaja como dato en `personalizacion.contexto_usuario`, nunca dentro del system prompt.', max_length=4000)),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones de quien pide el análisis (`personalizacion.instrucciones_usuario`). Ajustan énfasis y tono; el formato del informe es fijo por contrato.', max_length=4000)),
                ('personalizacion_momentos', models.JSONField(blank=True, default=list, help_text='Lista de {"momento": <id>, "contexto": "…", "instrucciones": "…"} — como máximo una entrada por momento del alcance.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('error_mensaje', models.TextField(blank=True)),
                ('entrada', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Salida kunsamu.analisis/v2 validada.')),
                ('diagnostico', models.JSONField(blank=True, default=dict)),
                ('version_prompt', models.CharField(blank=True, max_length=40)),
                ('version_esquema', models.CharField(blank=True, max_length=40)),
                ('prompt_usado', models.TextField(blank=True)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_v2', to='jornadas.jornada')),
                ('momentos', models.ManyToManyField(blank=True, help_text='Vacío en modo integral (el alcance es toda la jornada). En por_momento, los momentos elegidos — el orden efectivo es por Momento.orden.', related_name='analisis_v2', to='jornadas.momento')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_v2_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis v2 (contrato kunsamu.analisis/v2)',
                'verbose_name_plural': 'Análisis v2 (contrato kunsamu.analisis/v2)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
