# Generated by Django 5.2.17 on 2026-09-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0017_analisis_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='infografiajornada',
            name='analisis_v2',
            field=models.ForeignKey(blank=True, help_text='Fija el AnalisisV2 (contrato kunsamu.analisis/v2) exacto del que salen los datos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infografias', to='analitica.analisisv2'),
        ),
    ]
