# Generated by Django 5.2.17 on 2026-09-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0018_infografia_analisis_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisjornadaia',
            name='diagnostico',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='entrada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='version_esquema',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='version_prompt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='diagnostico',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='entrada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='version_esquema',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='version_prompt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='reporte',
            name='diagnostico',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporte',
            name='entrada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporte',
            name='version_esquema',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='reporte',
            name='version_prompt',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
