# Generated by Django 5.2.17 on 2026-09-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0019_resultado_v2_en_analisis_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='kunsamu.presentacion/v1', max_length=40)),
                ('modelo', models.CharField(max_length=60)),
                ('diapositivas', models.JSONField(help_text='La secuencia recibida en el POST, tal cual — el backend nunca la reconstruye ni la altera, sólo la guarda y se la pasa al modelo.')),
                ('diseno', models.JSONField(help_text='Contrato kunsamu.presentacion/v1 ya saneado (ver presentacion_diseno_ia.py).')),
                ('correcciones', models.JSONField(blank=True, default=list)),
                ('assets', models.JSONField(blank=True, default=list, help_text='Ids de JornadaAsset enviados al modelo.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('analisis_jornada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_diseno', to='analitica.analisisjornadaia')),
                ('analisis_momento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_diseno', to='analitica.analisismomentoia')),
                ('reporte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_diseno', to='analitica.reporte')),
            ],
            options={
                'verbose_name': 'Diseño de presentación (IA)',
                'verbose_name_plural': 'Diseños de presentación (IA)',
            },
        ),
    ]
