# Generated by Django 5.2.17 on 2026-10-04 23:25

import django.db.models.deletion
from django.conf import settings
from pathlib import Path

from django.db import migrations, models

# La versión 1 de cada tipo es el texto que estaba en el código al momento de HU-92, copiado a
# `analitica/system_prompts_semilla/`. Esos archivos existen SOLO para esta siembra: lo que corre
# es la tabla. No editarlos — un cambio a un prompt es una versión nueva desde la API.
SEMILLA = Path(__file__).resolve().parent.parent / 'system_prompts_semilla'
# (etiqueta ≤ 60 caracteres, de dónde salió el texto)
ETIQUETAS = {
    'analisis_llm': ('v2.2 — analista principal', 'analitica/v2/recursos/SYSTEM_PROMPT_LLM.md'),
    'analisis_bertopic': ('v2.2', 'analitica/v2/recursos/SYSTEM_PROMPT_BERTOPIC.md'),
    'infografia': ('Prefijo de las láminas', 'infografia_ia_openai.SYSTEM_PROMPT_PREFIJO'),
    'presentacion': ('Presentación HTML', 'presentacion.SYSTEM_PROMPT'),
    'presentacion_diseno': ('Diagramación (HU §6)', 'presentacion_diseno_ia.SYSTEM_PROMPT'),
    'sugerencias': ('Sugerencias del análisis guiado', 'sugerencias_ia_openai.SYSTEM_PROMPT'),
}


def sembrar(apps, schema_editor):
    from django.utils import timezone

    SystemPrompt = apps.get_model('analitica', 'SystemPrompt')
    ahora = timezone.now()
    for tipo, (etiqueta, origen) in ETIQUETAS.items():
        if SystemPrompt.objects.filter(tipo=tipo).exists():
            continue
        SystemPrompt.objects.create(
            tipo=tipo, version=1, etiqueta=etiqueta,
            notas=(
                'Versión inicial: el texto que usaba el código antes de mover los prompts a la '
                f'tabla (HU-92), tomado de `{origen}`.'
            ),
            contenido=(SEMILLA / f'{tipo}.md').read_text(encoding='utf-8'),
            activo=True, activado_en=ahora,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0020_presentacion_diseno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infografiajornada',
            name='version_prompt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='presentaciondiseno',
            name='version_prompt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presentacion_version_prompt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('analisis_llm', 'Análisis — pipeline LLM'), ('analisis_bertopic', 'Análisis — pipeline BERTopic + LLM'), ('infografia', 'Infografía (prompt base de las láminas)'), ('presentacion', 'Presentación HTML de un reporte'), ('presentacion_diseno', 'Diseño de presentación (diagramación)'), ('sugerencias', 'Sugerencias para el análisis guiado')], max_length=30)),
                ('version', models.PositiveIntegerField(editable=False)),
                ('etiqueta', models.CharField(blank=True, help_text='Nombre corto opcional para reconocerla (ej. "v2.2 analista principal").', max_length=60)),
                ('notas', models.TextField(blank=True, help_text='Qué cambia respecto de la anterior y por qué.')),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=False, editable=False)),
                ('activado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_prompts_activados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_prompts_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', '-version'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'version'), name='system_prompt_version_unica'), models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('tipo',), name='system_prompt_un_activo_por_tipo')],
            },
        ),
        migrations.RunPython(sembrar, migrations.RunPython.noop),
    ]
