# Generated by Django 5.2.17 on 2026-10-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0021_system_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisjornadaia',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general que escribió quien pidió el análisis — puede coincidir con Jornada.descripcion o no. Se guarda tal cual, sin normalizar.'),
        ),
        migrations.AlterField(
            model_name='analisisjornadaia',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales de quien pidió el análisis (tono, público, cantidad de gráficos, idioma…) — mandan sobre el estilo y la estructura por defecto.'),
        ),
        migrations.AlterField(
            model_name='analisismomentoia',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general que escribió quien pidió el análisis — puede coincidir con Jornada.descripcion o no. Se guarda tal cual, sin normalizar.'),
        ),
        migrations.AlterField(
            model_name='analisismomentoia',
            name='contexto_momento',
            field=models.TextField(blank=True, help_text='Contexto propio de ESTE momento, además del contexto general de la jornada. Solo aplica cuando el alcance es un único momento.'),
        ),
        migrations.AlterField(
            model_name='analisismomentoia',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales de quien pidió el análisis (tono, público, cantidad de gráficos, idioma…) — mandan sobre el estilo y la estructura por defecto.'),
        ),
        migrations.AlterField(
            model_name='analisismomentoia',
            name='instrucciones_momento',
            field=models.TextField(blank=True, help_text='Instrucciones propias de ESTE momento, además de las generales. Solo aplica cuando el alcance es un único momento.'),
        ),
        migrations.AlterField(
            model_name='analisisv2',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general escrito por quien pide el análisis. Viaja como dato en `personalizacion.contexto_usuario`, nunca dentro del system prompt.'),
        ),
        migrations.AlterField(
            model_name='analisisv2',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones de quien pide el análisis (`personalizacion.instrucciones_usuario`). Ajustan énfasis y tono; el formato del informe es fijo por contrato.'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto general que escribió quien pidió el análisis — puede coincidir con Jornada.descripcion o no. Se guarda tal cual, sin normalizar.'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='contexto_momento',
            field=models.TextField(blank=True, help_text='Contexto propio de ESTE momento, además del contexto general de la jornada. Solo aplica cuando el alcance es un único momento.'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales de quien pidió el análisis (tono, público, cantidad de gráficos, idioma…) — mandan sobre el estilo y la estructura por defecto.'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='instrucciones_momento',
            field=models.TextField(blank=True, help_text='Instrucciones propias de ESTE momento, además de las generales. Solo aplica cuando el alcance es un único momento.'),
        ),
    ]
