# Generated by Django 5.2.17 on 2026-10-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0022_sin_tope_texto_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisjornadaia',
            name='consultado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='esfuerzo_solicitado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='fase_openai',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='flex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='modelo_solicitado',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='analisisjornadaia',
            name='respuesta_openai_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
