# Generated by Django 5.2.17 on 2026-10-05 03:04

import django.db.models.deletion
from django.conf import settings
from pathlib import Path

from django.db import migrations, models

SEMILLA = Path(__file__).resolve().parent.parent / 'system_prompts_semilla' / 'resumen_presentacion.md'


def sembrar(apps, schema_editor):
    """Versión 1, activa, del prompt del resumen para presentación (HU-99). El archivo existe solo
    para esta siembra: lo que corre es la tabla."""
    from django.utils import timezone

    SystemPrompt = apps.get_model('analitica', 'SystemPrompt')
    if SystemPrompt.objects.filter(tipo='resumen_presentacion').exists():
        return
    SystemPrompt.objects.create(
        tipo='resumen_presentacion', version=1, etiqueta='Resumen para diapositivas',
        notas='Versión inicial (HU-99).', contenido=SEMILLA.read_text(encoding='utf-8'),
        activo=True, activado_en=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0023_analisis_jornada_background'),
        ('jornadas', '0017_momento_backfill_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='tipo',
            field=models.CharField(choices=[('analisis_llm', 'Análisis — pipeline LLM'), ('analisis_bertopic', 'Análisis — pipeline BERTopic + LLM'), ('infografia', 'Infografía (prompt base de las láminas)'), ('presentacion', 'Presentación HTML de un reporte'), ('presentacion_diseno', 'Diseño de presentación (diagramación)'), ('sugerencias', 'Sugerencias para el análisis guiado'), ('resumen_presentacion', 'Resumen de un análisis para presentar en diapositivas')], max_length=30),
        ),
        migrations.CreateModel(
            name='ResumenPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucciones', models.TextField(blank=True, help_text='Público, duración, cantidad de diapositivas, énfasis… Sin tope de largo.')),
                ('modelo_solicitado', models.CharField(blank=True, max_length=80)),
                ('esfuerzo_solicitado', models.CharField(blank=True, max_length=10)),
                ('flex', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Salida `kunsamu.analisis/v2` validada.')),
                ('entrada', models.JSONField(blank=True, default=dict)),
                ('diagnostico', models.JSONField(blank=True, default=dict)),
                ('prompt_usado', models.TextField(blank=True)),
                ('version_prompt', models.CharField(blank=True, max_length=40)),
                ('version_esquema', models.CharField(blank=True, max_length=40)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('error_mensaje', models.TextField(blank=True)),
                ('respuesta_openai_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('fase_openai', models.CharField(blank=True, max_length=12)),
                ('consultado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('analisis_jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_presentacion', to='analitica.analisisjornadaia')),
                ('analisis_momento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_presentacion', to='analitica.analisismomentoia')),
                ('analisis_v2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_presentacion', to='analitica.analisisv2')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_presentacion', to='jornadas.jornada')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_presentacion', to='analitica.reporte')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_presentacion_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen para presentación',
                'verbose_name_plural': 'Resúmenes para presentación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RunPython(sembrar, migrations.RunPython.noop),
    ]
