# Generated by Django 5.2.17 on 2026-10-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0024_resumen_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisjornadaia',
            name='adjuntos',
            field=models.JSONField(blank=True, default=list, help_text='Documentos/imágenes de la jornada (JornadaAsset) sumados al análisis (HU-101): lista de {"asset": <id>, "uso": "fuente"|"contexto"}. Ver analitica/v2/adjuntos.py.'),
        ),
        migrations.AddField(
            model_name='analisismomentoia',
            name='adjuntos',
            field=models.JSONField(blank=True, default=list, help_text='Documentos/imágenes de la jornada (JornadaAsset) sumados al análisis (HU-101): lista de {"asset": <id>, "uso": "fuente"|"contexto"}. Ver analitica/v2/adjuntos.py.'),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='adjuntos',
            field=models.JSONField(blank=True, default=list, help_text='Documentos/imágenes de la jornada (JornadaAsset) sumados al análisis (HU-101): lista de {"asset": <id>, "uso": "fuente"|"contexto"}. Ver analitica/v2/adjuntos.py.'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='adjuntos',
            field=models.JSONField(blank=True, default=list, help_text='Documentos/imágenes de la jornada (JornadaAsset) sumados al análisis (HU-101): lista de {"asset": <id>, "uso": "fuente"|"contexto"}. Ver analitica/v2/adjuntos.py.'),
        ),
        migrations.AddField(
            model_name='resumenpresentacion',
            name='adjuntos',
            field=models.JSONField(blank=True, default=list, help_text='Ids de JornadaAsset que entran como contexto del resumen (HU-101). Solo contexto: un resumen no puede sumar fuentes que el análisis original no tenía.'),
        ),
    ]
