# Generated by Django 5.2.17 on 2026-10-06 03:10

import django.db.models.deletion
from pathlib import Path

from django.db import migrations, models

SEMILLA = Path(__file__).resolve().parent.parent / 'system_prompts_semilla' / 'ajuste_analisis.md'


def sembrar(apps, schema_editor):
    """Versión 1, activa, del prompt del ajuste (HU-102). Se SUMA al prompt activo del análisis
    (ver analitica/ajuste_analisis.py). El archivo existe solo para esta siembra: lo que corre es la
    tabla."""
    from django.utils import timezone

    SystemPrompt = apps.get_model('analitica', 'SystemPrompt')
    if SystemPrompt.objects.filter(tipo='ajuste_analisis').exists():
        return
    SystemPrompt.objects.create(
        tipo='ajuste_analisis', version=1, etiqueta='Ajuste de un análisis',
        notas='Versión inicial (HU-102).', contenido=SEMILLA.read_text(encoding='utf-8'),
        activo=True, activado_en=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0025_adjuntos_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisv2',
            name='ajuste_de_analisis_jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='analitica.analisisjornadaia'),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='ajuste_de_analisis_momento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='analitica.analisismomentoia'),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='ajuste_de_analisis_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='analitica.analisisv2'),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='ajuste_de_reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='analitica.reporte'),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='consultado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='es_ajuste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='esfuerzo_solicitado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='fase_openai',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='flex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='modelo_solicitado',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='analisisv2',
            name='respuesta_openai_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='tipo',
            field=models.CharField(choices=[('analisis_llm', 'Análisis — pipeline LLM'), ('analisis_bertopic', 'Análisis — pipeline BERTopic + LLM'), ('infografia', 'Infografía (prompt base de las láminas)'), ('presentacion', 'Presentación HTML de un reporte'), ('presentacion_diseno', 'Diseño de presentación (diagramación)'), ('sugerencias', 'Sugerencias para el análisis guiado'), ('resumen_presentacion', 'Resumen de un análisis para presentar en diapositivas'), ('ajuste_analisis', 'Ajuste de un análisis ya entregado (se suma al prompt del análisis)')], max_length=30),
        ),
        migrations.RunPython(sembrar, migrations.RunPython.noop),
    ]
