# Generated by Django 5.2.17 on 2026-09-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0006_momento_mesas_permitidas'),
        ('transcripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiontranscripcion',
            name='incluir_en_analisis_jornada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesiontranscripcion',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripciones', to='jornadas.jornada'),
        ),
    ]
