# Generated by Django 5.2.17 on 2026-09-11 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('abierta', 'Abierta'), ('unica', 'Selección única'), ('multiple', 'Selección múltiple'), ('matriz', 'Matriz comparativa (filas × columnas)')], max_length=20)),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField()),
                ('obligatoria', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos_creados', to=settings.AUTH_USER_MODEL)),
                ('encargados', models.ManyToManyField(blank=True, related_name='instrumentos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPreguntaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='instrumentos.preguntainstrumento')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='FilaMatrizInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='instrumentos.preguntainstrumento')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ColumnaMatrizInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='instrumentos.preguntainstrumento')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='PreregistroInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistros_creados', to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preregistrados', to='instrumentos.instrumento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('instrumento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='AplicacionInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_revision', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('preregistro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacion', to='instrumentos.preregistroinstrumento')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('contenido', 'Contenido (solo lectura)'), ('preguntas', 'Preguntas (a diligenciar)')], default='contenido', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='instrumentos.instrumento')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('instrumento', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='preguntainstrumento',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='instrumentos.seccioninstrumento'),
        ),
        migrations.CreateModel(
            name='RespuestaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_libre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='instrumentos.aplicacioninstrumento')),
                ('columna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentos.columnamatrizinstrumento')),
                ('fila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentos.filamatrizinstrumento')),
                ('opciones', models.ManyToManyField(blank=True, related_name='respuestas', to='instrumentos.opcionpreguntainstrumento')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='instrumentos.preguntainstrumento')),
            ],
            options={
                'unique_together': {('aplicacion', 'pregunta', 'fila', 'columna')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='preguntainstrumento',
            unique_together={('seccion', 'orden')},
        ),
    ]
