# Generated by Django 5.2.17 on 2026-09-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
        ('jornadas', '0006_momento_mesas_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='jornadas.jornada'),
        ),
    ]
