# Generated by Django 5.2.17 on 2026-09-15 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_instrumento_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacioninstrumento',
            name='generado_por_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExtraccionInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='instrumentos/extracciones/%Y/%m/')),
                ('nombre_archivo_original', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('preguntas_omitidas', models.JSONField(blank=True, default=list)),
                ('error_mensaje', models.TextField(blank=True)),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('aplicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraccion_origen', to='instrumentos.aplicacioninstrumento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones', to='instrumentos.instrumento')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones_instrumento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracción de instrumento con IA (documento diligenciado)',
                'verbose_name_plural': 'Extracciones de instrumento con IA (documentos diligenciados)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
