# Generated by Django 5.2.17 on 2026-09-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_aplicacioninstrumento_generado_por_ia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extraccioninstrumento',
            name='responsable_detectado',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extraccioninstrumento',
            name='responsable_estado',
            field=models.CharField(choices=[('no_buscado', 'No se buscó (responsable indicado a mano)'), ('sin_dato', 'El documento no traía responsable'), ('emparejado', 'Emparejado con una persona'), ('ambiguo', 'Ambiguo — varias personas coinciden'), ('sin_coincidencia', 'Sin coincidencia')], default='no_buscado', max_length=20),
        ),
        migrations.AddField(
            model_name='extraccioninstrumento',
            name='resultado_crudo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='permite_carga_archivo',
            field=models.BooleanField(default=False, help_text='Si los usuarios preregistrados pueden subir ellos mismos un documento diligenciado para que la IA lo transcriba. Apagado = solo un administrador puede hacerlo.'),
        ),
        migrations.AlterField(
            model_name='extraccioninstrumento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completo', 'Completo'), ('sin_responsable', 'Transcrito — falta asignar responsable'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='extraccioninstrumento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracciones_instrumento', to=settings.AUTH_USER_MODEL),
        ),
    ]
