# Generated by Django 4.2.30 on 2026-09-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0004_extraccioninstrumento_responsable_detectado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='permite_carga_archivo',
        ),
    ]
