# Generated by Django 5.2.17 on 2026-10-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0006_responsable_estado_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraccioninstrumento',
            name='responsable_estado',
            field=models.CharField(choices=[('no_buscado', 'No se buscó (responsable indicado a mano)'), ('sin_dato', 'El documento no traía responsable'), ('emparejado', 'Emparejado con una persona'), ('ambiguo', 'Ambiguo — varias personas coinciden'), ('sin_coincidencia', 'Sin coincidencia'), ('creado', 'Creado a partir del documento'), ('con_respuestas', 'Ya tiene respuestas en el momento — hay que decidir')], default='no_buscado', max_length=20),
        ),
    ]
